In [1]:
import numpy as np
import matplotlib as plt
import pandas as pd

In [2]:
data = pd.read_csv(r'F:\New folder\creditcardfraud\creditcard.csv')

In [3]:
data.head(5)

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [4]:
x = data.iloc[:,[1,2,3,4,29]]

In [5]:
x

V1         V2        V3        V4  Amount
0       -1.359807  -0.072781  2.536347  1.378155  149.62
1        1.191857   0.266151  0.166480  0.448154    2.69
2       -1.358354  -1.340163  1.773209  0.379780  378.66
3       -0.966272  -0.185226  1.792993 -0.863291  123.50
4       -1.158233   0.877737  1.548718  0.403034   69.99
5       -0.425966   0.960523  1.141109 -0.168252    3.67
6        1.229658   0.141004  0.045371  1.202613    4.99
7       -0.644269   1.417964  1.074380 -0.492199   40.80
8       -0.894286   0.286157 -0.113192 -0.271526   93.20
9       -0.338262   1.119593  1.044367 -0.222187    3.68
10       1.449044  -1.176339  0.913860 -1.375667    7.80
11       0.384978   0.616109 -0.874300 -0.094019    9.99
12       1.249999  -1.221637  0.383930 -1.234899  121.50
13       1.069374   0.287722  0.828613  2.712520   27.50
14      -2.791855  -0.327771  1.641750  1.767473   58.80
15      -0.752417   0.345485  2.057323 -1.468643   15.99
16       1.103215  -0.040296  1.267332  1.289091   12.99
17      -0.436905   0.918966  0.924591 -0.727219    0.89
18      -5.401258  -5.450148  1.186305  1.736239   46.80
19       1.492936  -1.029346  0.454795 -1.438026    5.00
20       0.694885  -1.361819  1.029221  0.834159  231.71
21       0.962496   0.328461 -0.171479  2.109204   34.09
22       1.166616   0.502120 -0.067300  2.261569    2.28
23       0.247491   0.277666  1.185471 -0.092603   22.75
24      -1.946525  -0.044901 -0.405570 -1.013057    0.89
25      -2.074295  -0.121482  1.322021  0.410008   26.43
26       1.173285   0.353498  0.283905  1.133563   41.88
27       1.322707  -0.174041  0.434555  0.576038   16.00
28      -0.414289   0.905437  1.727453  1.473471   33.00
29       1.059387  -0.175319  1.266130  1.186110   12.99
...           ...        ...       ...       ...     ...
284777   2.079137  -0.028723 -1.343392  0.358000    1.00
284778  -0.764523   0.588379 -0.907599 -0.418847   80.00
284779   1.975178  -0.616244 -2.628295 -0.406246   25.00
284780  -1.727503   1.108356  2.219561  1.148583   30.00
284781  -1.139015  -0.155510  1.894478 -1.138957   13.00
284782  -0.268061   2.540315 -1.400915  4.846661   12.82
284783  -1.796092   1.929178 -2.828417 -1.689844   11.46
284784  -0.669662   0.923769 -1.543167 -1.560729   40.00
284785   0.032887   0.545338 -1.185844 -1.729828    1.79
284786  -2.076175   2.142238 -2.522704 -1.888063    8.95
284787  -1.029719  -1.110670 -0.636179 -0.840816    9.99
284788   2.007418  -0.280235 -0.208113  0.335261    3.99
284789  -0.446951   1.302212 -0.168583  0.981577   60.50
284790  -0.515513   0.971950 -1.014580 -0.677037    9.81
284791  -0.863506   0.874701  0.420358 -0.530365   20.32
284792  -0.724123   1.485216 -1.132218 -0.607190    3.99
284793   1.971002  -0.699067 -1.697541 -0.617643    4.99
284794  -1.266580  -0.400461  0.956221 -0.723919    0.89
284795 -12.516732  10.187818 -8.476671 -2.510473    9.87
284796   1.884849  -0.143540 -0.999943  1.506772   60.00
284797  -0.241923   0.712247  0.399806 -0.463406    5.49
284798   0.219529   0.881246 -0.635891  0.960928   24.05
284799  -1.775135  -0.004235  1.189786  0.331096   79.99
284800   2.039560  -0.175233 -1.196825  0.234580    2.68
284801   0.120316   0.931005 -0.546012 -0.745097    2.69
284802 -11.881118  10.071785 -9.834783 -2.066656    0.77
284803  -0.732789  -0.055080  2.035030 -0.738589   24.79
284804   1.919565  -0.301254 -3.249640 -0.557828   67.88
284805  -0.240440   0.530483  0.702510  0.689799   10.00
284806  -0.533413  -0.189733  0.703337 -0.506271  217.00

[284807 rows x 5 columns]

In [6]:
x = data.iloc[:,[1,2,3,4,29]].values

In [7]:
x

array([[-1.35980713e+00, -7.27811733e-02,  2.53634674e+00,
         1.37815522e+00,  1.49620000e+02],
       [ 1.19185711e+00,  2.66150712e-01,  1.66480113e-01,
         4.48154078e-01,  2.69000000e+00],
       [-1.35835406e+00, -1.34016307e+00,  1.77320934e+00,
         3.79779593e-01,  3.78660000e+02],
       ...,
       [ 1.91956501e+00, -3.01253846e-01, -3.24963981e+00,
        -5.57828125e-01,  6.78800000e+01],
       [-2.40440050e-01,  5.30482513e-01,  7.02510230e-01,
         6.89799168e-01,  1.00000000e+01],
       [-5.33412522e-01, -1.89733337e-01,  7.03337367e-01,
        -5.06271240e-01,  2.17000000e+02]])

In [8]:
y = data.iloc[:,30]

In [9]:
y

0         0
1         0
2         0
3         0
4         0
5         0
6         0
7         0
8         0
9         0
10        0
11        0
12        0
13        0
14        0
15        0
16        0
17        0
18        0
19        0
20        0
21        0
22        0
23        0
24        0
25        0
26        0
27        0
28        0
29        0
         ..
284777    0
284778    0
284779    0
284780    0
284781    0
284782    0
284783    0
284784    0
284785    0
284786    0
284787    0
284788    0
284789    0
284790    0
284791    0
284792    0
284793    0
284794    0
284795    0
284796    0
284797    0
284798    0
284799    0
284800    0
284801    0
284802    0
284803    0
284804    0
284805    0
284806    0
Name: Class, Length: 284807, dtype: int64

In [10]:
import matplotlib.pyplot as plt

In [11]:
y = data.iloc[:,30].values

In [12]:
x.shape

(284807, 5)

In [13]:
import numpy as np

In [14]:
x.shape

(284807, 5)

In [15]:
    y

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [16]:
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler(feature_range = (0, 1))
x_scaled = sc.fit_transform(x)

In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)

In [18]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
x_train =sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [19]:
import keras
from keras.models import Sequential
from keras.layers import Dense


Using TensorFlow backend.


In [20]:
model=Sequential()

W0716 14:15:58.496831 13412 deprecation_wrapper.py:119] From F:\manideep\lib\site-packages\keras\backend\tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.



In [21]:
x.shape

(284807, 5)

In [22]:
x_train.shape

(199364, 5)

In [23]:
model.add(Dense(input_dim=5,init="random_uniform",activation='relu',output_dim=10))#input layer

F:\manideep\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=5, activation="relu", units=10, kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.
W0716 14:15:58.746698 13412 deprecation_wrapper.py:119] From F:\manideep\lib\site-packages\keras\backend\tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0716 14:15:58.755271 13412 deprecation_wrapper.py:119] From F:\manideep\lib\site-packages\keras\backend\tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.



In [24]:
model.add(Dense(output_dim=5,init="random_uniform",activation='relu'))#hidden layer

F:\manideep\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=5, kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [25]:
model.add(Dense(output_dim=1,init='random_uniform',activation='sigmoid'))#output layer

F:\manideep\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [26]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])#adam=batch gradent descent

W0716 14:15:59.014301 13412 deprecation_wrapper.py:119] From F:\manideep\lib\site-packages\keras\optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0716 14:15:59.050752 13412 deprecation_wrapper.py:119] From F:\manideep\lib\site-packages\keras\backend\tensorflow_backend.py:3376: The name tf.log is deprecated. Please use tf.math.log instead.

W0716 14:15:59.060411 13412 deprecation.py:323] From F:\manideep\lib\site-packages\tensorflow\python\ops\nn_impl.py:180: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [27]:
model.fit(x_train,y_train,epochs=20,batch_size=32)#epochs no of iteration 

W0716 14:15:59.468602 13412 deprecation_wrapper.py:119] From F:\manideep\lib\site-packages\keras\backend\tensorflow_backend.py:986: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.



Epoch 1/20
199364/199364 [==============================] - 12s 60us/step - loss: 0.0250 - acc: 0.9982
Epoch 2/20
199364/199364 [==============================] - 11s 58us/step - loss: 0.0053 - acc: 0.9987
Epoch 3/20
199364/199364 [==============================] - 12s 58us/step - loss: 0.0051 - acc: 0.9989
Epoch 4/20
199364/199364 [==============================] - 11s 57us/step - loss: 0.0050 - acc: 0.9989
Epoch 5/20
199364/199364 [==============================] - 12s 58us/step - loss: 0.0050 - acc: 0.9989
Epoch 6/20
199364/199364 [==============================] - 12s 58us/step - loss: 0.0049 - acc: 0.9989
Epoch 7/20
199364/199364 [==============================] - 12s 58us/step - loss: 0.0049 - acc: 0.9989
Epoch 8/20
199364/199364 [==============================] - 12s 59us/step - loss: 0.0049 - acc: 0.9989
Epoch 9/20
199364/199364 [==============================] - 12s 59us/step - loss: 0.0049 - acc: 0.9989
Epoch 10/20
199364/199364 [==============================] - 12s 59us/ste

In [28]:
y_pred = model.predict(x_test)

In [29]:
y_pred

array([[1.21980906e-04],
       [1.18702650e-04],
       [1.26126409e-03],
       ...,
       [1.76032051e-03],
       [7.95451706e-05],
       [3.07339686e-03]], dtype=float32)

In [30]:
y_pred=(y_pred>0.5)

In [31]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [32]:
y_test

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [33]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)


from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.9989232587807076

In [34]:
y_p=model.predict(sc.transform(np.array([[5,5,9,3,5]])))


F:\manideep\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [35]:
y_p

array([[0.]], dtype=float32)

In [36]:
y_p=(y_p>0.5)

In [37]:
y_p

array([[False]])